icsvortex666/GA-Hunter

.gitignore, package.json
This will setup the basic packages for our project, I also added some extras to the gitignore.
If you guys want I can explain it.
=> setup initial node packages and add extras to .gitignore

app/app.js, dist/index.html, server.js, webpack.config.js
I had to create/modify the following files in order to render: server.js; app/app.js; dist/index.html; webpack.config.js
=> render hello world on localhost:3000

app/app.js, client/components/App.jsx, client/index.jsx, dist/index.html, dist/stylesheets/master.css, dist/stylesheets/normalize.css, package.json, server.js
Just some fixes to @tmulroy last pull request, added additional react components and styling
=> fix weird spacing, add basic components and initial styling

.gitignore, client/components/Modal.jsx, client/index.jsx, package.json
imported react modal and added to package.json, commented out App component in Index.jsx simply for testing of ModalView (which I imagine we can just comment out and keep a long string of commented versions until we're ready to start putting things together?).  Modal is functional.
=> imports react-modal as a dependency and sets up dummy modal view for testing

client/components/Modal.jsx, client/components/ProjectModalView.jsx
add a ProjectModalView component, which renders a project inside the modal window on open.  Commit includes touching ProjectModalView.jsx, populating with dummy information, exporting component, and adding it to Modal component
=> add a dynamic project modal view inside the modal window

app/config/sql/project/all.sql, app/config/sql/project/create.sql, app/config/sql/project/delete.sql, app/config/sql/project/find.sql
This PR creates four sql queries for the projects table: all (finds all projects); create(inserts a new project); delete(deletes a project by id) and find(finds an entry by any column equaling any value)
=> User sql/all

app/config/sqlProvider.js
This PR adds 'projects' to sqlProvider so we can call a projectDAO in the future
=> add projects to sqlProvider

app/models/User.js
small fix, change createdAt to created
=> small fix to user model file

app/config/sqlProvider.js, app/services/ProjectDAO.js
creates project DAO file, fixes a small typo in sqlProvider.  Checked it out, seems to work for all DAO methods
=> Project dao

app/config/sql/upvote/all.sql, app/config/sql/upvote/create.sql, app/config/sql/upvote/delete.sql, app/config/sql/upvote/find.sql, app/config/sqlProvider.js, app/services/UpvoteDAO.js
This PR creates the UpvotesDAO and associated sql queries.
=> Upvotes dao

app/config/sql/category/all.sql, app/config/sql/category/create.sql, app/config/sql/category/delete.sql, app/config/sql/category/find.sql, app/config/sqlProvider.js, app/services/CategoryDAO.js
This PR adds the CategoriesDAO.
=> Categories dao

app/config/sql/projects_users/all.sql, app/config/sql/projects_users/create.sql, app/config/sql/projects_users/delete.sql, app/config/sql/projects_users/find.sql, app/config/sqlProvider.js, app/models/ProjectUser.js, app/services/Projects_UsersDAO.js
creates projectsusers dao, adds sql files, fixes an error in model for projects users object constructor
=> Projects users dao

app/services/Projects_UsersDAO.js
fixes a bug i created by not removing the serial id from the DAO create method
=> fixes a bug in Projects Users DAO's create function.

app/app.js, app/controllers/AuthController.js, app/services/UserDAO.js
Implement a working POST request to /api/users
**NOTE** all fields are required: name, email, password, course
=> Get projects

client/components/SignUp.jsx
This PR will connect the frontend register form to the backend users table. Once the 'register' button is clicked, a post request is sent to api/users with the values name, email, password, and course taken from the form.
=> Registration form

client/components/Login.jsx
This PR adds the values in the frontend login form to the database by sending a post request to api/login.
=> create an onChange and onSubmit that sends a post request to api/login

app/app.js, app/routes/projectRouter.js
allow routing for the Project Controller
=> App routing

app/controllers/UserController.js, app/routes/userRouter.js, app/services/UserDAO.js
update the user controller and router and DAO to allow updates and deletes of users
=> User controller

app/app.js, app/controllers/CommentsController.js, app/routes/commentRouter.js
create the comments controller and the router, adjust the app.js to comment back in the relevant lines
=> Comments controller

app/controllers/UpvoteController.js, app/routes/upvoteRouter.js
fixing small error i made in upvoteRouter
=> fixing small bug in the upvoteRouter

client/components/App.jsx, client/components/Login.jsx, client/components/UpvoteView.jsx
fixes the routing issue that i had caused by changing around the login
=> Upvote functionality

app/controllers/ProjectController.js
add a newly-created project's id to projects_users
=> Edit delete
